# Generated by Django 5.2.7 on 2025-10-14 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\+375\\d{9}$', message='Неверный формат номера (+375XXXXXXXXX)')]),
        ),
    ]
