services:
  web:
    build: ./
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /app
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
    volumes:
      - .:/app 

  bot:
    build: ./
    env_file:
      - ./.env
    depends_on:
      - db
    working_dir: /app
    volumes:
      - .:/app
    command: python manage.py run_bot
  
  redis:
    image: redis:7

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: face2face
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 177886936
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_face2face
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "6060:80"
    depends_on:
      - db

volumes:
  postgres_data:
