# Generated by Django 5.2.14 on 2026-05-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', 'init_cosmetologist_data_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
