# Generated by Django 5.2.7 on 2025-11-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='procedure',
        ),
    ]
