# Generated by Django 5.2.14 on 2026-06-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_category_procedure_issale_procedure_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='isSale',
        ),
    ]
