# Generated by Django 5.2.7 on 2025-12-06 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_appointment_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='procedure',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.procedure'),
            preserve_default=False,
        ),
    ]
