# Generated by Django 5.2.10 on 2026-01-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='procedure',
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='procedures',
            field=models.ManyToManyField(related_name='bookings', to='booking.procedure'),
        ),
    ]
