# Generated by Django 5.2.14 on 2026-06-01 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_procedure_issale'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='buffer_time',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
    ]
