# Generated by Django 5.2.10 on 2026-01-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_procedure_booking_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
