# Generated by Django 5.2.10 on 2026-01-28 06:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from datetime import timedelta


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='appointment',
        ),
        migrations.AddField(
            model_name='booking',
            name='cosmetologist',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='booking.cosmetologist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 28, 6, 45, 48, 899369, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.DurationField(default=timedelta(minutes=30)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='procedures',
            field=models.ManyToManyField(to='booking.procedure'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_working', models.BooleanField(default=True)),
                ('cosmetologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='booking.cosmetologist')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='booking.workday')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
