# Generated by Django 5.2.10 on 2026-04-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_appointment_booking_cosmetologist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetologist',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
