# Generated by Django 5.2.12 on 2026-04-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_cosmetologist_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmetologist',
            name='avatar',
        ),
        migrations.AddField(
            model_name='cosmetologist',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
