# Generated by Django 5.2.13 on 2026-04-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_cosmetologist_avatar_cosmetologist_avatar_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
